
version: 2

models:
  - name: observations
    description: "Parses observations from raw table. Incremental build."
    config:
      contract:
        enforced: true
    constraints:
      - type: primary_key
        columns: [id]
      - type: foreign_key
        columns: [species_id, genus_id]
    columns:
      - name: id
        description: "Shares the key value from GBIF occurence/search endpoint."
        constraints:
          - not_null
      - name: species_id
        description: "FK to specimens.id"
        constraints:
          - not_null
      - name: genus_id
        description: "FK to genera.id"
        constraints:
          - not_null